### ISSUE TITLE
OSSObject 怎么设置

### ISSUE THREAD

**Issue by InTheClodus** [lucky1213/aliyun_oss#11]
![image](https://user-images.githubusercontent.com/33110499/135659393-1a4b9c9a-5f1c-4d17-9bf4-fe3d8ebf12cf.png)
这一块出错，但是没看到文档说怎么配置OSSObject

**Comment by wl386123298** [comment]
如果是从文件的话，这样
`
 OSSImageObject.fromFile(file: File(image.path)
`
字节流的话
`
OSSImageObject.fromBytes(bytes:xxx )
`

**Comment by InTheClodus** [comment]
> 如果是从文件的话，这样 `OSSImageObject.fromFile(file: File(image.path)` 字节流的话 `OSSImageObject.fromBytes(bytes:xxx )`

好的，十分感谢，我都差点忘了这个东西了 😂
