### ISSUE TITLE
在最后的时候出现错误

### ISSUE THREAD

**Issue by shaoting0730** [lucky1213/aliyun_oss#13]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/14305431/154884758-41d24737-8a17-4051-9478-04a4212b5ad7.png">
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/14305431/154884824-6ebe8bb2-04ad-4110-9314-f1e3e66cfc28.png">
这个问题该如何解决呢？

**Comment by lucky1213** [comment]
抱歉，我这边参数没有描述准确，path参数是文件夹路径，是指上传到指定aliyun上的某个文件夹
