### ISSUE TITLE
InvalidAccessKeyId

### ISSUE THREAD

**Issue by realcarlos** [lucky1213/aliyun_oss#19]
I/flutter ( 3569): <Error>
I/flutter ( 3569):   <Code>InvalidAccessKeyId</Code>
I/flutter ( 3569):   <Message>The OSS Access Key Id you provided does not exist in our records. The Security Token may be lost to specify that it is a STS Access Id.</Message>
I/flutter ( 3569):   <RequestId>64DCFBB694C77F3830309BB0</RequestId>
I/flutter ( 3569):   <HostId>paper-data-uat.oss-cn-hangzhou.aliyuncs.com</HostId>
I/flutter ( 3569):   <OSSAccessKeyId>STS.NUQrpkhEPr98RDscmwTiUMKdc</OSSAccessKeyId>
I/flutter ( 3569):   <EC>0002-00000003</EC>
I/flutter ( 3569): </Error>

这是初始化的代码;

/// 初始化aliyun oss
`                        OSSClient.init(
                          endpoint: resp.data.endpoint,
                          bucket: resp.data.bucket,
                          credentials: () {
                            // Or Credentials Config
                            return Future.value(Credentials(
                              accessKeyId: resp.data.accessKeyId,
                              accessKeySecret: resp.data.accessKeySecret,
                              securityToken: resp.data.stsToken
                            ));
                          },
                        );`

这是上传的代码：
`final object = await OSSClient().putObject(
                          object: OSSImageObject.fromFile(file: File(path)),
                          bucket: state.bucket, // String?
                          endpoint: state.endpoint, // String?
                        );
`

不明白为什么这里还要设置bucket和endpoint

**Comment by lucky1213** [comment]
可以不设置，如果上传时指定则根据指定的bucket和endpoint完成单次上传，大部分情况无需再上传时指定
