### ISSUE TITLE
如何使用OSS，有具体的使用方法吗？

### ISSUE THREAD

**Issue by xmy1231** [lucky1213/aliyun_oss#2]
Credentials.fromJson 这个方法一直报错

**Comment by lucky1213** [comment]
> Credentials.fromJson 这个方法一直报错

项目比较着急，后续会增加上示例代码，Credentials内主要是accessKeyId，accessKeySecret的设置，以及支持使用securityToken和过期时间，securityToken不为null时对应header内的x-oss-security-token

**Comment by xmy1231** [comment]
没关系 ，我自己手动撸撸一个 ，谢谢大佬的支持！
